name: First exercise
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Lint init
              run: echo "executando o lint"
            - name: execucao lint
              run: npm run lint

    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: test init
              run: echo "executando o teste"
            - name: execucao test
              run: npm run test
    
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Deploy init
              run: echo "executando deploy"
            - name: execucao deploy
              run: npm run build